### ISSUE TITLE
bug，应用切换后，多个界面会重叠到一起

### ISSUE THREAD

**Issue by lonelyleaf** [Arachnid-27/Cimoc#11]
还没看源代码，fragment生命周期没处理好？

**Comment by Arachnid-27** [comment]
是这样的，fragment我是一开始全部创建好，然后通过hide和show来切换的，切换应用后可能是系统销毁了Activity，调用onSaveInstance保存状态，下次打开后自动恢复fragment重新add进去了，这个我在dev-1.4.x分支里尝试解决了，单纯的注释掉onSaveInstance函数的内容，也就是不自动保存状态，暂时没有副作用

**Comment by lonelyleaf** [comment]
fragment的生命周期确实讨厌……我自己做app很不喜欢用onSaveInstanceState去保存状态，宁愿每次都重新new一个
