### ISSUE TITLE
能不能增加这个网站的插件

### ISSUE THREAD

**Issue by 1608637229** [Arachnid-27/Cimoc#14]
一个韩国漫画网站，http://www.webtoons.com/zh-hans/，有漫画还是不错的，默认下滑阅读比较好，如果作者有时间的话！

**Comment by Arachnid-27** [comment]
已增加，由于变化不大，所以暂时不更新版本，需要的话可以在dev-1.4.x自行编译，顺便在设置里加了个卷纸模式下取消图片间隔，方便看条漫，因为自己不怎么看这类漫画，写的有问题的话欢迎反馈！
