### ISSUE TITLE
感谢作者的制作吧，

### ISSUE THREAD

**Issue by 1608637229** [Arachnid-27/Cimoc#15]
再提供两个网站吧，一个新新动漫http://3g.77mh.com/(手机版网页)，电脑版网页http://www.77mh.com/，主要是腐漫画比较多，但是其他资源也还可以，比如几个主要的网页漫画站都屏蔽了东京喰种第一季，只有汗汗漫画能看，新新可以作为一个备选吧，
还有一个绅士站177漫画：http://www.177pic66.com/  ，主要是单行本本子，有汉化和生肉两种，不错的网站吧，希望能有插件。  
    有时间的话可以做下，话说作者是不是不想太高调啊，酷安以前上架过又下架了，嘿嘿

**Comment by Arachnid-27** [comment]
好的，有空看看，上架不是我上的，不想上架是因为这个软件算空闲时间做的，没有太多精力去维护和添加新功能，只能慢慢来，这样感觉不太负责

**Comment by 1608637229** [comment]
谢谢，177这个网站真心还不错

**Comment by 1608637229** [comment]
手机汗汗这个插件部分漫画封面提示盗链了

**Comment by Arachnid-27** [comment]
好像没什么办法，用手机浏览器看也是显示盗链

**Comment by saasddsaasdd** [comment]
请问能否添加一些大厂源？比如网易漫画

**Comment by Arachnid-27** [comment]
@saasddsaasdd 不打算加了……
