### ISSUE TITLE
首次安装后打开就会提示读取最后阅读失败

### ISSUE THREAD

**Issue by 1608637229** [Arachnid-27/Cimoc#17]
还有个意见，目前只能依靠搜索漫画找漫画吗，要是能进去到每个插件就好了，有时候不知道看什么就不好找漫画了，希望能进入插件，类似于H view哪种体验！

**Comment by Arachnid-27** [comment]
这个我知道，没影响所以懒得改了……明天更新，新版本点图源可以看到最近更新的漫画
