### ISSUE TITLE
增加主题确实不错，但是夜间模式等于没了，

### ISSUE THREAD

**Issue by 1608637229** [Arachnid-27/Cimoc#19]
上个版本的夜间模式挺好的，这个版本仅仅只是调低亮度而已，希望可以改回上个版本的夜间模式，还有换主题能不重启吗，能做到不重启最好。

**Comment by Arachnid-27** [comment]
因为那个黑色主题配色方面比较麻烦，有点难统一，所以暂时删掉了，下次看能不能加上吧
换主题不重启应该可以，就是写起来会比较麻烦……以后有时间再说吧
