### ISSUE TITLE
很奇怪的问题

### ISSUE THREAD

**Issue by 1608637229** [Arachnid-27/Cimoc#21]
这两个问题都是在我使用免流的前提下，不开免流也没问题。
最后阅读点击进去如果解析错误然后退回到首页后就会停止运行。但是不开免流则不会FC，
57漫画看不到内容，能看到目录，但具体内容解析不出来，用手机浏览器（UC和Via都测试了）免流下测试能看而且速度还挺快的。不免流就没这两个问题，也不知道为什么？
最后一点建议，能否韩国条漫默认卷纸上下模式，其它漫画翻页左右。条漫我喜欢卷纸上下看，普通漫画我喜欢翻页左右看，然而现在的设置是全局设置，不能针对每个站点设置。

**Comment by Arachnid-27** [comment]
新版本在阅读状态下切换阅读模式
