### ISSUE TITLE
自定义存储路径的问题。。

### ISSUE THREAD

**Issue by jcyxxx** [Arachnid-27/Cimoc#25]
可不可以把自定义存储路径这个功能改成一个界面化的像文件管理器那样的选择路径的东西，或者简单粗暴改成“内置储存”和”外置储存”这么两个选项。。。
我这里的情况是，不管输入什么路径都会显示写入失败，哪怕是默认的路径，所以只能下载到默认路径。
而且应该不是设备的问题，无论是我的三星A9还是kindle fire都会这样。
求解。。

**Comment by Arachnid-27** [comment]
原本是想调用系统的，但是4.4以上有新API和4.4以下要分开写，当时觉得有点麻烦就搞了个简单的填路径，这阵子没空不想写……
