### ISSUE TITLE
请问漫画页面的解析这块是怎么完成的。。

### ISSUE THREAD

**Issue by MarxD** [Arachnid-27/Cimoc#26]
想用java写个爬虫上dm5给kindle下点资源，但是源码里的解析方式看不太懂。。能稍微讲解一下吗？或者有类似的动态解析方案的文章链接也可以，万分感谢！

**Comment by Arachnid-27** [comment]
是指漫画图片吗？http://www.dm5.com/m<漫画ID>/chapterfun.ashx?cid=<章节ID>&page=<页码>
这个接口可以拿到图片地址，返回的js代码混淆过，需要解密一下

**Comment by MarxD** [comment]
有一个小问题。。我现在能拿到接口地址，类似
http://www.dm5.com/m6445/chapterfun.ashx?cid=6445&page=1&key=c3935c046f085589
这个一样，但是用这个接口获取图片地址的混淆代码的时候，如果一段时间没发送请求，再次发送的时候不会返回任何数据，把接口地址在浏览器里输入进去也没有数据，然后我如果用浏览器打开一下http://www.dm5.com/m6445/这个页面，然后代码这边就能继续获取了。。我试了试解析接口地址的时候保存cookie，然后后续发送请求的时候带上这个cookie，发现也没用，key也一直都没变，发送请求的时候还包括什么头文件吗？我用浏览器控制台看请求数据好像没有什么特殊的地方。。望赐教
![123](https://cloud.githubusercontent.com/assets/17312932/20534616/c60e0e80-b11c-11e6-90e7-9e82f702f2ac.jpg)

**Comment by Arachnid-27** [comment]
@MarxD 试试在header加上Referer:http://www.dm5.com

**Comment by MarxD** [comment]
@Arachnid-27 能获取了，多谢！
