### ISSUE TITLE
感觉有些源有问题，网络状况很好的情况下总会自动暂停下载。

### ISSUE THREAD

**Issue by jcyxxx** [Arachnid-27/Cimoc#31]
总会下载个十几秒到几分钟的时间就自动暂停，而且下载速度很慢。
除了手机汗汗这个源，这个源会一直到下载完成，但其他的总有上述问题。

**Comment by jcyxxx** [comment]
好像感觉不对。。
是某些源在下载单行本的时候有问题。。
下载单话好像都没问题。。

**Comment by Arachnid-27** [comment]
更新下吧，自动暂停的问题应该解决了，但是下载速度慢好像没什么办法
