### ISSUE TITLE
点击检查更新无法自动更新版本

### ISSUE THREAD

**Issue by longous** [Arachnid-27/Cimoc#33]
点击检查更新无法自动更新版本,这个要怎么实现呢？每次重新下载安装有点麻烦

**Comment by Arachnid-27** [comment]
我觉得用第三方 sdk 或者用 github release 的地址都行，目前用的度盘，没研究过，估计拿下载链接比较难，但是不想加 sdk，用 github 的话怕有些人连不上

**Comment by longous** [comment]
哦哦，好的，感谢回复！
