### ISSUE TITLE
有没有可能实现添加本地的压缩包漫画，或者文件夹漫画

### ISSUE THREAD

**Issue by 1608637229** [Arachnid-27/Cimoc#35]
说白了就是支持添加本地漫画(我下好的本子)，还有一个建议，在阅读漫画的界面增加一个小图标实现横屏和竖屏的切换。

**Comment by 1608637229** [comment]
还是希望能恢复以前自定义添加源，不知道那几个源还是否支持=_=

**Comment by Arachnid-27** [comment]
实现应该是可能，但是最近想搞别的东西，不想写这个……
横竖屏切换在阅读设置，点击事件里面可以选择
那几个H站图源有点搞事，不想加回去

**Comment by 1608637229** [comment]
H站图源默认隐藏啊（作为隐藏福利），其实这软件很低调了，我觉得阅读体验和外观真的很难得，所以如何以后有时间，希望可以实现添加本地漫画，顺便已捐赠，希望能维护吧

**Comment by wufakanqingweilai** [comment]
手机汗汗源失效了

**Comment by Arachnid-27** [comment]
支持本地漫画了，只支持文件夹形式的，暂时不支持压缩包
