### ISSUE TITLE
能不能保存漫画最后浏览卷回的名称信息

### ISSUE THREAD

**Issue by liyfa** [Arachnid-27/Cimoc#38]
这样即使漫画源失效，在漫画页面里也能显示最后浏览的第几回或第几卷信息
方便更换其他漫画源后，可以最快找到并同步漫画浏览进度

**Comment by Arachnid-27** [comment]
加了这个功能，更新一下吧，长按封面，然后选择漫画信息即可，但是因为以前没有保存这项信息，所以以前的漫画需要看过一次后才会有

**Comment by liyfa** [comment]
新版本在手机和平板都安装后，看到漫画信息选项中的最后阅读和时间
发现个问题，我在手机上把所有漫画都点了一遍，然后备份收藏文件传到平板上，想通过恢复收藏来同步所有漫画信息，但是恢复后平板上的漫画信息栏中最后阅读和时间还都是null

**Comment by Arachnid-27** [comment]
这个……我发现我备份时最后章节存错位置了，阅读时间是 null 倒是正常的，话又说回来，你竟然把所有漫画都点了一遍……

**Comment by liyfa** [comment]
强迫症发作，受不了部分漫画有阅读信息，部分没有的状况
