### ISSUE TITLE
漫画是从这些漫画网站用爬虫弄下来的还是有api key什么的？

### ISSUE THREAD

**Issue by VanishingDante** [Arachnid-27/Cimoc#4]
漫画是从这些漫画网站用爬虫弄下来的还是有api key什么的？
Java 不熟，源码看着好恼火

a岛的串找不到了，也记不清楚你在上面留邮箱没有了，没有你的联系方式，所以就在这开了个issue

**Comment by Arachnid-27** [comment]
用的爬虫
