### ISSUE TITLE
较旧设备上的大图片加载问题

### ISSUE THREAD

**Issue by nichbar** [Arachnid-27/Cimoc#49]
在较旧的设备(一加1)上遇到了一个Bitmap过大的问题
> [Bitmap too large to be uploaded into a texture](https://stackoverflow.com/questions/10271020/bitmap-too-large-to-be-uploaded-into-a-texture)

是那种长图型的漫画，可参考此[图片](http://3.p.mpcdn.net/49601/1082554/2.jpg)或于搜索中搜索MangaNel漫画Tomorrow。该图片高为6078 px，超过了一加1上的最大渲染Bitmap 4096 x 4096，于是就直接加载不了了(一加3上没有此问题)。

我见您在[ReaderAdapter](https://github.com/Arachnid-27/Cimoc/blob/96c025ed22fbc4452bc5e473351238e6a950e58d/app/src/main/java/com/hiroshi/cimoc/ui/adapter/ReaderAdapter.java#L212)里也有一个是否 resize 的判断，可是貌似代码对在线图片没有效果，而且 resize 的效果也不太好(把图片 resize 得太小)。

我觉得依照不同设备的渲染 bitmap 最大值来做一个界限来进行 resize 可以达到一个比较好的效果。

因为水平有限我就不乱改然后 pull requests 了 ಠ_ಠ ，have a nice day.

**Comment by Arachnid-27** [comment]
昨天更新的那个版本，开了切图以后可以看吗？

**Comment by nichbar** [comment]
可以了
