### ISSUE TITLE
看漫画时双指放大、缩小图片时，触发了滑动ViewPager

### ISSUE THREAD

**Issue by wordplat** [Arachnid-27/Cimoc#7]
发生的条件是：两只手指同时放大或缩小

**Comment by Arachnid-27** [comment]
试了5分钟没试出来，是不是单击了屏幕左边或者右边？

**Comment by wordplat** [comment]
没有单击操作，要两只手指同时缩小，不能一只手指动、一只手指不动，要同时移动缩小才会触发。
可用剪刀手（食指和中指在屏幕对角上放着，然后咔嚓一下），就发生了这个BUG。

**Comment by Arachnid-27** [comment]
感谢反馈，似乎已经解决了，或者说概率变得很低了，因为试了几十次也没有出现这个问题
由于我用的是RecyclerViewPager库，里面似乎没有对多点触控的特殊情况判断，我通过加上一些判断解决了

**Comment by Arachnid-27** [comment]
个人感觉这个问题不太影响正常使用，而且晚上才更新过一个版本，所以就先暂时不更新了
