### ISSUE TITLE
求加个一键把所有收藏漫画的源换到别的源

### ISSUE THREAD

**Issue by Huang454** [Arachnid-27/Cimoc#78]
看漫画源有时能用有时不能，我收藏了他二百多漫画现在想全转到别的源。二百多漫画手动搜索收藏要好久

**Comment by feilongfl** [comment]
@Huang454 这个貌似不好实现，因为这个软件依赖的是各个动漫站的搜索页，如果要实现这个功能估计要建立漫画的数据库了:fearful:

**Comment by zhongfly** [comment]
@feilongfl 我觉得不必完全一键，做到简化操作即可，操作可以这样
批量换源：
⑴选中所有要换源的漫画
⑵每个漫画按顺序重复以下动作：
①按标题搜索
②搜索页中，用户从结果中选择来源，当：按下收藏/“下一个”/选择来源（不打开漫画详情页）时 便完成此漫画换源
③下一个漫画

 @Huang454 这样就足够方便了，再加上搜索限定死来源，应该就够了吧

**Comment by feilongfl** [comment]
@zhongfly 
哦，这样，看来我想的有点复杂了

@Huang454 
我修复了一下看漫画的源，我觉得这样比批量换源实用一些😀
> https://github.com/Arachnid-27/Cimoc/issues/84
