### ISSUE TITLE
Android 6.X 请求存储权限时, 确认后崩溃

### ISSUE THREAD

**Issue by Smallpath** [Arachnid-27/Cimoc#9]

**Comment by Arachnid-27** [comment]
这个我重现不了，我这边确认后可以正常下载，因为是业余的，所以6.0权限这块我也不太熟就是了

**Comment by zpf527** [comment]
权限申请的可以看下这个项目，希望能帮到！！！
https://github.com/lypeer/FcPermissions

**Comment by Arachnid-27** [comment]
@zpf527 好的，有空我看看，谢谢！
